export let topSkills = [
  "Data Entry Specialists",
  "Video Editors",
  "Data Analyst",
  "Shopify Developer",
  "Ruby on Rails Developer",
  "Android Developer",
  "Bookkeeper",
  "Content Writer",
  "Copywriter",
  "Database Administrator",
  "Data Scientist",
  "Front-End Developer",
  "Game Developer",
  "Graphic Designer",
  "iOS Developer",
  "Java Developer",
  "JavaScript Developer",
  "Logo Designer",
  "Mobile App Developer",
  "PHP Developer",
  "Python Developer",
  "Resume Writer",
  "SEO Expert",
  "Social Media Manager",
  "Software Developer",
  "Software Engineer",
  "Technical Writer",
  "UI Designer",
  "UX Designer",
  "Virtual Assistant",
  "Web Designer",
  "Wordpress Developer",
];

export let trendingSkills = [
  "Blockchain",
  "Go development",
  "Node.js",
  "Vue.js",
  "HR consulting",
  "Microsoft Power BI",
  "Instructional design",
  "React.js",
  "Videographers",
  "HTML5 Developers",
  "Ghostwriters",
  "Unity 3D Developers",
  "Business Consultants",
  "Coders",
  "Marketing Consultants",
  "Web Developers",
  "Illustrators",
  "Google AdWords Experts",
  "Digital Marketers",
  "Project Managers",
  "Arduino Programmers",
  "Ruby Developers",
  "AngularJS Devleopers",
  "Full Stack Developers",
  "Email Marketing Consultants",
  "React Native Developers",
  "Swift Developers",
  "CSS Developers",
  "Google Sketchup Freelancers",
  "Back End Developers",
  "Smartsheet Freelancers",
  "Zoom Video Conferencing Freelancers",
];
